# Generated by Django 4.2.10 on 2024-03-10 16:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='born',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='account',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='account',
            name='height',
            field=models.FloatField(default=170, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(70)]),
        ),
        migrations.AddField(
            model_name='account',
            name='spend_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='account',
            name='weight',
            field=models.FloatField(default=70, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
