# Generated by Django 4.2.11 on 2024-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mybackend", "0003_account_all_landmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="video_detail",
            field=models.JSONField(default={}),
        ),
    ]
